name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Debug tree
        run: |
          pwd
          ls -la
          echo "--- Assignments/Assignment6 ---"
          ls -la Assignments/Assignment6 || true
          echo "--- src ---"
          ls -la Assignments/Assignment6/src || true
          echo "--- tests ---"
          ls -la Assignments/Assignment6/tests || true

      - name: Run tests (with coverage)
        env:
          PYTHONPATH: ${{ github.workspace }}/Assignments/Assignment6/src
        run: |
          cd Assignments/Assignment6
          python -m pytest --cov=src --cov-report=term-missing -q