name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Assignments/Assignment6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      # Optional: debug to verify paths/files in CI
      - name: Show tree
        run: |
          pwd
          ls -la
          echo "--- src ---"
          ls -la src || true
          echo "--- tests ---"
          ls -la tests || true
          echo "--- pytest.ini ---"
          cat pytest.ini || echo "no pytest.ini"

      - name: Run tests (with coverage)
        env:
          PYTHONPATH: src
        run: |
          python -m pytest --cov=src --cov-report=term-missing -q